### ISSUE TITLE
Questions about using this Repo

### ISSUE THREAD

**Issue by RepoCreator** [rsdev69/Lenovo-E560-Clover#1]
Hi Sergey,
Thank you very much for you work.

I have E560 laptop but I have an i5 CPU, could I use the same files in this repo? or should I change something?

Another question is about bios, I didn't upgrade my bios and I have v1.13 because I read that updating bios could make some problems with hackintosh, did you upgraded you bios? and what version you have?

and lastly, should I put the EFI folder in this repo in USB flash drive that I will use it to install macOS?
I would be grateful if you give me a link to a guide that I should follow to install macOS on my laptop.

Thank you again for your work on this and sorry for asking a lot of questions.

**Comment by hoanuchiha98** [comment]
I am using same laptop, what patch dsdt please

**Comment by Rsdev69** [comment]
# The easiest way to install ...
1. Download this torrent https://rutracker.org/forum/viewtopic.php?t=5571139
2. Do everything on this video https://www.youtube.com/watch?v=nhAVUHWNNaw&feature=youtu.be
3. When the previous two items are done, you just need to replace in your usb flash drive folder **Clover/EFI**  on my **EFI** from this repo.
4. Good luck with the installation)

**Comment by Rsdev69** [comment]
> Hi Sergey,
> Thank you very much for you work.
> 
> I have E560 laptop but I have an i5 CPU, could I use the same files in this repo? or should I change something?
> 
> Another question is about bios, I didn't upgrade my bios and I have v1.13 because I read that updating bios could make some problems with hackintosh, did you upgraded you bios? and what version you have?
> 
> and lastly, should I put the EFI folder in this repo in USB flash drive that I will use it to install macOS?
> I would be grateful if you give me a link to a guide that I should follow to install macOS on my laptop.
> 
> Thank you again for your work on this and sorry for asking a lot of questions.

# The easiest way to install ...
1. Download this torrent https://rutracker.org/forum/viewtopic.php?t=5571139
2. Do everything on this video https://www.youtube.com/watch?v=nhAVUHWNNaw&feature=youtu.be
3. When the previous two items are done, you just need to replace in your usb flash drive folder **Clover/EFI**  on my **EFI** from this repo.
4. Good luck with the installation)

**Comment by hoanuchiha98** [comment]
I use ThinkPad 560 to same you. You patch dsdt what
Thank you very much

Vào 18:57, Th 5, 11 thg 10, 2018 Sergey Rodin <notifications@github.com> đã
viết:
