### ISSUE TITLE
how to update 10.15.2

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/Lenovo-E560-Clover#10]
Hi.
I was able to replace the efi folder you just introduced Install version 10.15.  
Now I want to update to version 10.15.2. 
After downloading this version and restarting, in the middle of the line under the Apple logo, the system will restart again and the line will not end.  
What version of Clover should I use, or what other efi folder should I use to fix the issue of version 10.15.2?  
please help. 🙏🏻🙏🏻
Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsdev69** [comment]
You cannot install the update because the system boots automatically from disk without delaying the choice of the update itself.
To update, you need to remove from config.plist fast boot option. After downloading update, restart and choose manually in boot menu new update.
<img width="477" alt="Screenshot1" src="https://user-images.githubusercontent.com/34169770/71159255-f6ffb200-224d-11ea-91c1-4da1ad2979d8.png">

**Comment by javadmahmoodi** [comment]
>You cannot install the update because the system boots automatically from disk without delaying the choice of the update. ...

@rsdev69 


Will deleting the config.plist file on the computer disk, and then running the update, will automatically show up and restart successfully when the system restarts?  And do I need to re-insert the config.plist file into the computer disk after the update?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsdev69** [comment]
> > You cannot install the update because the system boots automatically from disk without delaying the choice of the update. ...
> 
> @rsdev69
> 
> Will deleting the config.plist file on the computer disk, and then running the update, will automatically show up and restart successfully when the system restarts? And do I need to re-insert the config.plist file into the computer disk after the update?
> 
> Sent with [GitHawk](http://githawk.com)

[config.plist.zip](https://github.com/rsdev69/Lenovo-E560-Clover/files/3987481/config.plist.zip)
Try update with this config.
