### ISSUE TITLE
Sleep issue

### ISSUE THREAD

**Issue by procodingtools** [rsdev69/Lenovo-E560-Clover#11]
Hi.

First, i want to thank you for this great job.
I have an issue about sleep. After wakeup, i have only black screen with mouse pointer.

My system is i5-6200u with R7 m370.

What should i do?

**Comment by rsdev69** [comment]
Hi, sleep is working 50/50
It works well with an external monitor, but sometimes it goes into reboot or a black screen. This is normal for hackintosh.

**Comment by rsdev69** [comment]
> Hi.
> 
> First, i want to thank you for this great job.
> I have an issue about sleep. After wakeup, i have only black screen with mouse pointer.
> 
> My system is i5-6200u with R7 m370.
> 
> What should i do?

Hi, sleep is working 50/50
It works well with an external monitor, but sometimes it goes into reboot or a black screen. This is normal for hackintosh.

**Comment by procodingtools** [comment]
> > Hi.
> > First, i want to thank you for this great job.
> > I have an issue about sleep. After wakeup, i have only black screen with mouse pointer.
> > My system is i5-6200u with R7 m370.
> > What should i do?
> 
> Hi, sleep is working 50/50
> It works well with an external monitor, but sometimes after wake up it goes into reboot or a black screen. This is normal for hackintosh.

Thnak you for replaying. But my hackintosh always displays black screen with mouse after wake. It's not sometimes.
Anything can help?

**Comment by rsdev69** [comment]
> Thnak you for replaying. But my hackintosh always displays black screen with mouse after wake. It's not sometimes.
> Anything can help?
Try boot with darkwake=1..10. Sometimes the right setting helps with sleep. 
![image](https://user-images.githubusercontent.com/34169770/75089558-a4e74f80-5562-11ea-87eb-0fc4692dc8eb.png)

**Comment by procodingtools** [comment]
> > Thnak you for replaying. But my hackintosh always displays black screen with mouse after wake. It's not sometimes.
> > Anything can help?
> 
> Try boot with darkwake=0..10. Sometimes the right setting helps with sleep.
> ![image](https://user-images.githubusercontent.com/34169770/75089558-a4e74f80-5562-11ea-87eb-0fc4692dc8eb.png)

I tried them all, but sorry no luck.

**Comment by rsdev69** [comment]
> I tried them all, but sorry no luck.

Some laptop will sleeping and wake problem which has discrete graphics card. Try disable discrete card with DSDT. I think methods _PTS for sleep and _WAK method for wake don't work through discrete card.

**Comment by procodingtools** [comment]
I'm already using HibernationFixup kext, but the discrete card is not already deactivated in the provided DSDT? because as I know macOS can't even start with an existing discrete card.

**Comment by rsdev69** [comment]
> I'm already using the HibernationFixup kext, but the discrete card is not already deactivated in the provided DSDT? because as I know macOS can't even start with an existing discrete card.

As I know, to disable a discrete card, you need a clean dsdt from the laptop where is this card exist. Find the method responsible for the card and turn it off or disable in bios.

**Comment by procodingtools** [comment]
Solved, just add -wegnoegpu whatevergreen bootflag it wil disable the discrete card.
works better with catalina updtae
