### ISSUE TITLE
how to update my clover to Clover r5104.

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/Lenovo-E560-Clover#12]
how to update **my clover** to **Clover r5104**. 

I'm a beginner and haven't done it because I'm afraid of something going on with Clover.  Please explain step by step to do this correctly. 
🙏🏻🌹🙏🏻🌹🙏🏻

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsdev69** [comment]
1. Open Clover Configurator.
[CCG.zip](https://github.com/rsdev69/Lenovo-E560-Clover/files/4266801/CCG.zip)
2. Mount EFI folder
<img width="1279" alt="Screenshot 2020-02-28 at 13 16 16" src="https://user-images.githubusercontent.com/34169770/75544788-57b92100-5a2d-11ea-8f33-eb1a5f9b65b6.png">
3. Delete old EFI folder and paste new from this repo.
<img width="768" alt="Screenshot 2020-02-28 at 13 17 32" src="https://user-images.githubusercontent.com/34169770/75544866-846d3880-5a2d-11ea-9b68-4653f5d5f511.png">
