### ISSUE TITLE
Better ALPS kext

### ISSUE THREAD

**Issue by procodingtools** [rsdev69/Lenovo-E560-Clover#13]
Hi rsdev69, i found a good kext for the ALPS trackpad and i suggest you to replace the old one by this.
Which working:
  - TrackPoint
  - 3 top buttons (right, middle and left)
  - Scrolling using middle button and trackpoint
  - Detectable by the trackpad prefpane
  - 2/3 multifinger gesture (to move between destops, just change shortcut in the 
     keyboard section)

Known issues:
  - Caps lock not working properly
  - Insert button not working
  - Dragging by physical left button (holding the left button and swipe touchpad) not working.
    If you touch the trackpad while holding the left button, the system will simulate a button 
    release.
  - May be other (let me know)

Best Regards

[VoodooPS2Controller.kext.zip](https://github.com/rsdev69/Lenovo-E560-Clover/files/4332833/VoodooPS2Controller.kext.zip)

**Comment by rsdev69** [comment]
I use the latest version VoodooPS2Controller. It works on the principle of mouse. To emulate swipe, can be used SmartScroll app. Other kext work not correct.
