### ISSUE TITLE
How to install mac os 10.15.4

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/Lenovo-E560-Clover#15]
Hi.  
I put the clover r5105 in the EFI folder.  Then I downloaded version 10.15.4 of Mac and clicked Install.  But it only displays the Apple logo, and nothing happens.  
Help extinguish the problem.  
Thanks 🙏🏻🌹

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsdev69** [comment]
> Hi.
> I put the clover r5105 in the EFI folder. Then I downloaded version 10.15.4 of Mac and clicked Install. But it only displays the Apple logo, and nothing happens.
> Help extinguish the problem.
> Thanks 🙏🏻🌹
> 
> Sent with [GitHawk](http://githawk.com)

Try boot with this config
[config.plist.zip](https://github.com/rsdev69/Lenovo-E560-Clover/files/4450227/config.plist.zip)

**Comment by javadmahmoodi** [comment]
Hi.
 I replaced the file with my own file.  Then I made a boot flash with unibeast for Mac 10.15.4.
 Then I replaced the EFI folder with the flash boot folder. 
But the time of descent is only displayed on the Apple logo, and the bottom line is not displayed at all, and the installation remains unfinished.  
Can you give me your own EFI folder that supports Mac 10.15.4 for me to use?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
