### ISSUE TITLE
Install mac os 10.15.4

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/Lenovo-E560-Clover#16]
Hi. 
I replaced the your file config.plist with my own file.  Then I made a boot flash with unibeast for Mac 10.15.4.  
Then I replaced the EFI folder with the flash boot folder.  
But the time of descent is only displayed on the Apple logo, and the bottom line is not displayed at all, and the installation remains unfinished.  
Can you give me your own EFI folder that supports Mac 10.15.4 for me to use?🙏🏻🙏🏻🌹

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsdev69** [comment]
> Hi.
This clover I'm using right now
[EFI.zip](https://github.com/rsdev69/Lenovo-E560-Clover/files/4455884/EFI.zip)

**Comment by javadmahmoodi** [comment]
I was now able to install Mac 10.15.4 with a bootable with your EFI folder.  
There is only one problem, that in the boot section, the icons are shown in a very bad and ugly way.  
Like the picture below.  
Can you help me look beautiful?

![97A721D6-949F-49C0-923B-FC17E6182D02](https://user-images.githubusercontent.com/11042152/78905511-5d297280-7a93-11ea-93ef-599d23893fe8.jpeg)

**Comment by rsdev69** [comment]
> I was now able to install Mac 10.15.4 with a bootable with your EFI folder.
> There is only one problem, that in the boot section, the icons are shown in a very bad and ugly way.
> Like the picture below.
> Can you help me look beautiful?

I do not know what the problem with boot menu. My boot theme works.
Try changing the theme to any other  or make fast boot, then the system will immediately boot without selecting a disk.

**Comment by javadmahmoodi** [comment]
My next problem is that I double-booted my laptop beforehand, and in this boot menu, it doesn't show the Windows Zoo option. Also, in your previous EFI file, the boot menu was displayed correctly. Can I replace the previous EFI folder since I have now installed and running Mac 10.15.4? Could I have a problem with that?

**Comment by rsdev69** [comment]
> Could I have a problem with that?

These folders are the same. They has differ only in the file config.plist
In the first, I turned off fast boot, and you can see the boot menu. Second config turn on fast boot and mac boot from default disk. No more differences.
