### ISSUE TITLE
Jagged text on Laptop screen

### ISSUE THREAD

**Issue by arellanojv** [rsdev69/Lenovo-E560-Clover#17]
First, Thank you for this. Great job!

Display texts are jagged or distorted if change the display to scaled (More Space)

Is there a way to improve it?

Looks good on external monitor though. I'm using 1080p external monitor

**Comment by rsdev69** [comment]
> First, Thank you for this. Great job!
> 
> Display texts are jagged or distorted if change the display to scaled (More Space)
> 
> Is there a way to improve it?
> 
> Looks good on external monitor though. I'm using 1080p external monitor

Hi!
For a less clear font on the laptop screen need to use HIDPI option. For me it's 1366x768.
With this resolution a font is as smooth as possible on monitor laptop.
<img width="560" alt="5" src="https://user-images.githubusercontent.com/34169770/83951377-c0d4df80-a839-11ea-939b-a463c0b6fd90.png">
I hope this helps you:)

**Comment by arellanojv** [comment]
Looks like the developer of HIDPI released a new version

![Screen Shot 2020-06-08 at 8 43 13 AM](https://user-images.githubusercontent.com/3446149/83983868-5cfb0580-a964-11ea-84d0-9b435b9598ca.png)

when I input 1366x768 to the Manual input resolution option the results for is only 1600x900 max resolution it is not the same as shown on your screenshot.

![Screen Shot 2020-06-08 at 8 46 16 AM](https://user-images.githubusercontent.com/3446149/83983930-c549e700-a964-11ea-92e8-798ec1400d1b.png)

![Screen Shot 2020-06-08 at 8 46 33 AM](https://user-images.githubusercontent.com/3446149/83983938-cb3fc800-a964-11ea-9794-bfb4830a7e66.png)

Once HIDPI is installed. can we reconfigure this on clover instead?

**Comment by rsdev69** [comment]
> Once HIDPI is installed. can we reconfigure this on clover instead?

You do not need to write anything in clover. Now HIDPI works.
