### ISSUE TITLE
Battery Indicator Issues After Sleep

### ISSUE THREAD

**Issue by arellanojv** [rsdev69/Lenovo-E560-Clover#18]
The battery does not charge after sleep.

![Screen Shot 2020-06-15 at 11 12 33 AM](https://user-images.githubusercontent.com/3446149/84614652-57b83080-aef9-11ea-99f3-829348549147.png)

**Comment by rsdev69** [comment]
> The battery does not charge after sleep.

Hi, sleep problem i know and no solutions now. I don't use sleep.
Also have problems with hdmi port with last Catalina 10.15.5.
Try use 10.14.6 Mojave. There are no problems with sleep and hdmi.
