### ISSUE TITLE
WIFI能完美驱动吗？

### ISSUE THREAD

**Issue by wsqGIT** [rsdev69/Lenovo-E560-Clover#19]
请问无线网络是怎么解决的？是使用的Tp-link 725n免驱驱动吗？我问了客服说不能用

**Comment by rsdev69** [comment]
> 请问无线网络是怎么解决的？是使用的Tp-link 725n免驱驱动吗？我问了客服说不能用

Tp-link 725n works well on macOS Mojave and Catalina. No problem issue.

**Comment by wsqGIT** [comment]
我安装的版本是10.15.1，每次进入到安装页面后鼠标点击就会卡死，请问这是什么原因？

**Comment by rsdev69** [comment]
> 我安装的版本是10.15.1，每次进入到安装页面后鼠标点击就会卡死，请问这是什么原因？

To install use last OpenCore EFI and last macOS 10.15.6 
I think you have problem with NVRAM. Clean NVRAM and everything will be fine.
