### ISSUE TITLE
Internal Mic

### ISSUE THREAD

**Issue by muhviehstah** [rsdev69/Lenovo-E560-Clover#2]
the internal microphone is not working. are u using it / had tested it ?

**Comment by rsdev69** [comment]
Internal microphone work only witch **voodoohda.kext**
[voodoohda](https://sourceforge.net/projects/voodoohda)

**Comment by tosnelde** [comment]
When I use battery only, mic works.. but with an AC cable on, no mic input...

**Comment by rsdev69** [comment]
> the internal microphone is not working. are u using it / had tested it ?

internal microphone fixed!

**Comment by rsdev69** [comment]
> When I use battery only, mic works.. but with an AC cable on, no mic input...

internal microphone fixed!
