### ISSUE TITLE
Any tutorial to install it?

### ISSUE THREAD

**Issue by D36u92** [rsdev69/Lenovo-E560-Clover#3]
It works for e 570 top? And how can i install it?

**Comment by rsdev69** [comment]
> It works for e 570 top? And how can i install it?
I do not know, I can not check because I do not have ThinkPad e570. On E560 work good 10.12-10.14

**Comment by rsdev69** [comment]
> It works for e 570 top? And how can i install it?

Try this repo
[](https://github.com/tluck/Lenovo-T460-Clover)
