### ISSUE TITLE
Bios Settings

### ISSUE THREAD

**Issue by nimadeve** [rsdev69/Lenovo-E560-Clover#4]
Thanks for Lenovo-E560-Clover

But Please put here Bios Settings for Lenovo E560 , I can't execute Clover

**Comment by rsdev69** [comment]
> Thanks for Lenovo-E560-Clover
> 
> But Please put here Bios Settings for Lenovo E560 , I can't execute Clover

Csm bios     ->    disable
Boot only     ->    UEFI
SATA            ->    AHCI
Secure Boot->  disable
Other setting by default.

**Comment by nimadeve** [comment]
Thanks man !
