### ISSUE TITLE
install mac os catalina

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/Lenovo-E560-Clover#5]
Hello.  
I installed MacVersion 10.14 on my lenovo e560 laptop and all the features work fine. 
Now I want to install Mac Catalina.  How to make flash boot?  
and Where to download Mac catalina to make flash boot?
plz help me

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsdev69** [comment]
> Hello.
> I installed MacVersion 10.14 on my lenovo e560 laptop and all the features work fine.
> Now I want to install Mac Catalina. How to make flash boot?
> and Where to download Mac catalina to make flash boot?
> plz help me
> 
> Sent with [GitHawk](http://githawk.com)

Hello
If you already installed 10.14 on laptop, then just go to the App Store and download version 10.15, when you download you will be just install it, I did not see any problems with the installation on new version macOS.
If you want to install a clean installation, download the dmg image from the App Store and write it to a USB flash drive as it did make on 10.14
https://support.apple.com/en-us/HT201372
