### ISSUE TITLE
create bootble usb for catalina

### ISSUE THREAD

**Issue by javadmahmoodi** [rsdev69/Lenovo-E560-Clover#7]
Hello my friend.  How do I make a flash boot ?!  Is it possible to build a Maccatalina flash boot with the latest Unibest version?  How did you make the flash boot ?!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by javadmahmoodi** [comment]
??

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rsdev69** [comment]
Hi, i make bootable installer for macOS witch last dmg Catalina file + clover booloader
https://support.apple.com/sl-si/HT201372
https://github.com/Dids/clover-builder/releases
Unibest I do not use.
