### ISSUE TITLE
Opencore

### ISSUE THREAD

**Issue by muhviehstah** [rsdev69/Lenovo-E560-Clover#9]
Maybe you should migrate to Opencore.

acidanthera stopped clover support for their kexts .

when you need some help with the migration, feel free to ask.

**Comment by rsdev69** [comment]
I try soon configure this new bootloader. 
Thanks for watching this repo.

**Comment by giodani97** [comment]
Hi @rsdev69, can I share an OpenCore configuration based on your Clover Configuration?

**Comment by rsdev69** [comment]
> Hi @rsdev69, can I share an OpenCore configuration based on your Clover Configuration?

Share here, i add in repo your OpenCore configuration.

**Comment by giodani97** [comment]
I created a repository here: [link](https://github.com/giodani97/Lenovo-E560-OpenCore). Only problem is that sometimes it stops at `ACPI: Executed x blocks of module-level executable AML code` , so you need to restart and boot again

**Comment by rsdev69** [comment]
> I created a repository here: [link](https://github.com/giodani97/Lenovo-E560-OpenCore). Only problem is that sometimes it stops at `ACPI: Executed x blocks of module-level executable AML code` , so you need to restart and boot again. Also you need to add the smbios in the config.plist.

Good job, OpenCore in trend now.

**Comment by rajolm** [comment]
Hi @rsdev69 
I remember that you said you will create a new Repo for your OpenCore configuration, can you please tell me when you will do that?
also does the Trackpad gestures work for you? (like two fingure scroll and four fingers to show all apps)
the Trackpad gestures doesn't work for me :(

**Comment by rajolm** [comment]
> I created a repository here: [link](https://github.com/giodani97/Lenovo-E560-OpenCore). Only problem is that sometimes it stops at `ACPI: Executed x blocks of module-level executable AML code` , so you need to restart and boot again. Also you need to add the smbios in the config.plist.

Hi @giodani97 
Thank you very much for sharing your OpenCore configuration,
I have a few question:
1. does the OpenCore works better than Clover for you?
2. Do you have sleep working properly? I'm using Clover now and the sleep not work for me 
3. Can I continue use my current Dual boot when I move to OpenCore? currently I have two partitions, one for macOS and one for Windows, and I dual boot between them using Clover, Can I use the current partitions (I don't want to reformat) easily with OpenCore?

Thank you very much in advance

**Comment by muhviehstah** [comment]
1. yes
2. try disable amd gpu, worked for me
3. you can use clover side by side with oc. windows bootloader and even linux , i'm using grub to boot my wanted BL (Clover as backup. OC , OC.bk   Windows , Manjaro) 

Keep the SystemUUID from clover in the Opencore config

**Comment by rajolm** [comment]
>     1. yes
> 
>     2. try disable amd gpu, worked for me
> 
>     3. you can use clover side by side with oc. windows bootloader and even linux , i'm using grub to boot my wanted BL (Clover as backup. OC , OC.bk   Windows , Manjaro)
> 
> 
> Keep the SystemUUID from clover in the Opencore config

Hi @muhviehstah 
Thank you very much for your response
Can you tell me how I can disable amd gpu in macOS only not in Windows?

Also, do you have the same `ACPI: Executed x blocks of module-level executable AML code` problem as @giodani97 ?

Lastly, it will be very nice if you make a public Repo for your OpenCore configuration and share it with us

**Comment by muhviehstah** [comment]
> Hi @muhviehstah
> Thank you very much for your response
> Can you tell me how I can disable amd gpu in macOS only not in Windows?
> 
use the device property disable external gpu (see hackintool)

or simply use bootarg -wegnoegpu from Whatevergreen
